version: '3.4'

services:
  notionics:
    image: notionics
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      NOTION_TOKEN: "secret_xxxxyyyyyzzzzz"
      ACCESS_KEY: "xxxxxx"
      PUBLIC_HOST_URL: "http://127.0.0.1:5173/"      
    ports:
      - 5173:5173
